-keepclassmembers class com.autoclicker.claude.data.** { *; }
-keep class com.autoclicker.claude.data.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-keep class com.google.gson.** { *; }
